### PR TITLE
announcements page - Category tabs update

### LINKED ISSUE #145: page-request: announcements-page
**Do Fill in the below details before proceeding**

- Page Name : Announcements Page
- Page Type: Events 
- Link To Data: Connect Aswin Asok
- Expected Delivery Time: 13th Monday

**What impact will this page bring to the current state**
In the first iteration of the website there was a page where we would list all the events that has happened on mulearn. While we build the second iteration of the website, we missed out this page. This page would help people visiting our website to get a quick view on what all had happened

### PR DESCRIPTION
**Pull request by Basith-P**

### CODE REVIEW

**Comment by AswinAsok** [comment]
@Basith-P I Hope this page has been implemented. Kindly confirm the same so that i can close the issue

**Comment by AswinAsok** [comment]
Is the development of this page completed?. If so kindly give me a confirmation so that i can close the same

**Comment by Basith-P** [comment]
Yes you can close it. I will have this tendency to keep working on this if this is open. : |

**Comment by AswinAsok** [comment]
Ha, Alright

**Pull request merged**
