### PR TITLE
Add new team card

### PR DESCRIPTION
**Pull request by Basith-P**

### CODE REVIEW

**Comment by VinuBalagopalAP** [comment]
Tech team data missing in cards -> µ-Web | µ-JSON | µ-300 | µ-Bot | µ-UI

**Comment by VinuBalagopalAP** [comment]
1. Place the LinkedIn icon on the right-bottom side of the web view.
2. Bring back the old card format to the mobile view with the LinkedIn icon on the right-center of the card.

**Comment by Basith-P** [comment]
Updated

**Comment by VinuBalagopalAP** [comment]
Data missing | Execute Members Positions  -> Example: MD, Cofounder, etc

**Pull request merged**
