### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by Basith-P**

### CODE REVIEW

**Comment by VinuBalagopalAP** [comment]
1. Wiki Syllabus > Angel's pic not viewing

**Comment by VinuBalagopalAP** [comment]
2. About Project Awesome! not needed

**Comment by VinuBalagopalAP** [comment]
3. Event list to youtube videos | Hacktoberfest page

**Comment by Basith-P** [comment]
> 1. Wiki Syllabus > Angel's pic not viewing

Need a new link for Angel's Pic

**Comment by Basith-P** [comment]
> 3. Event list to youtube videos | Hacktoberfest page

Can't find git and Github session on YouTube

**Comment by VinuBalagopalAP** [comment]
1. Angel's pic - https://drive.google.com/file/d/1z2jWVsVFZ0iXxJ13BWrotGXvFbbhtN4N/edit

**Comment by VinuBalagopalAP** [comment]
2. Git and GitHub session on YouTubelink - https://youtu.be/va6LLfdhvGM

**Comment by Basith-P** [comment]
> 1. Angel's pic - https://drive.google.com/file/d/1z2jWVsVFZ0iXxJ13BWrotGXvFbbhtN4N/edit

The other existing images are not from the drive. The links look like this: https://media-exp1.licdn.com/dms/image/C4D03AQFRW9syB7WIUg/profile-displayphoto-shrink_200_200/0/1647073221043?e=1669852800&v=beta&t=sq888G3WyZJkfFIIR-M-Bvd1fc3aXcup0XSZqJ3-8TQ

**Pull request merged**
